---
- name: Install packages
  hosts: all
  vars:
    MOTD_IMPORTANT: "This is the default message"
    ESSENTIAL_PACKAGES:
      - tree
      - vim
      - git

  tasks:
   # - name: Open http firewalld port
   #   firewalld:
   #     service: http
   #     permanent: true
   #     state: enabled
   #     immediate: yes
   #   become: yes

    ## Install essential packages
    - name: add essential packages
      yum:
        name: "{{ item }}"
        state: latest
    ## This list is the name of the RPM's we are looking to install.
      with_items: "{{ ESSENTIAL_PACKAGES }}"
      become: yes


    - name: Install apache
      yum: name=httpd

    - name: start the httpd service
      service: name=httpd state=started enabled=yes
      notify:
      - restart apache


    - name: Build variable page
      template:
        src: dumpall.j2
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: "u=rwx,g=rx,o=rx"
        force: yes
      become: True

  handlers:
    - name: restart apache
      service: name=httpd state=restarted



