---
- name: Setup an EC2 instance
  hosts: all
  vars:

  tasks:
    - name: Create the Ansible group
      group:
        name: ansible
        state: present
        gid: 1337
      remote_user: ec2-user

    - name: Create the Ansible user and generate it's SSH key.
      user:
        name: ansible
        comment: "Ansible service account"
        uid: 1337
        group: ansible
        generate_ssh_key: yes
        state: present
      remote_user: ec2-user