
- name: Update the tower inventories
  hosts: localhost
  vars:
    tower_hostname: tower.shadowlab
    inventory_id: 3
    user: username
    password: password
  connection: local
  tasks:
    - name: Update the tower inventory from source
      {{ hostvars[groups['webservers'][0]]['ansible_eth0']['ipv4']['address'] }}
      uri:
        url: https://{{ tower_hostname }}/api/v2/inventories/{{ inventory_id }}/update_inventory_sources/
        method: GET
        headers:
          Content-Type: "application/json"
        username: "{{ user }}"
        password: "{{ password }}"
        validate_certs: no


