---
- name: Setup an EC2 instance
  hosts: localhost
  vars:
    key_name: towerv2
    region: eu-west-1
    zone: eu-west-1a
    instance_type: t2.micro
    image: ami-8b8c57f8
    security_group: ansible-security-group
    vpc_subnet_id: subnet-b4dd46d0
    vm_name: webserver
    vm_role: webserver
    vm_environment: production
    assign_public_ip: yes
    vm_count: 1


  connection: local
  tasks:
    - ec2_remote_facts:

    - name: Create an EC2 machine
      ec2:
        key_name: "{{ key_name }}"
        region: "{{ region }}"
        zone: "{{ zone }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: yes
        group: "{{ security_group }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        assign_public_ip: "{{ assign_public_ip }}"
        monitoring: no
        count: "{{ vm_count }}"
        state: present
        instance_tags:
          Name: "{{ vm_name }}"
          role: "{{ vm_role }}"
          environment:  "{{ vm_environment }}"
      register: newmachines


    - name: Wait for SSH to start
      wait_for:
        host: "{{ newmachines.instances[0].public_ip }}"
        port: 22
        timeout: 300
      delegate_to: localhost

    - name: Add the machine to in memory inventory
      add_host:
        hostname: "{{ newmachines.instances[0].public_ip }}"
        groups: amazon

    #- debug:
    #    msg: "{{ newmachines.instances[0].public_ip }}"

    #- debug:
    #    msg: "{{ hostvars[groups['amazon'][0]] }}"